[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200

# Gives access to deploy script to read/write to filesystem
fs_permissions = [{ access = "read-write", path = "./"}]


[fmt]
    line_length = 119

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
local="http://127.0.0.1:8545"
ethereum-sepolia="https://0xrpc.io/sep"
ethereum-mainnet="https://patient-solemn-forest.quiknode.pro/${QUICKNODE_API_KEY}/"
